/**
 * Shared DOCX content-diff helpers for the fidelity gates.
 *
 * Diff method: DOCX → HTML via mammoth (the sanctioned DOCX→text tool) → DOM via jsdom →
 * ordered list of block texts (paragraphs + table cells). We compare CONTENT, not byte/zip
 * identity (styling/metadata legitimately differ). For the LessonSequence the Section-C
 * Resource column is dropped from both sides before comparing (Lesson3 leaves it empty —
 * single-runtime, no Python recommender).
 */
import mammoth from 'mammoth'
import { JSDOM } from 'jsdom'

export const norm = (s: string) => s.replace(/\s+/g, ' ').trim()

/** Remove the Resource column from every Section-C table (matched by its 'Resource' header). */
export function stripResourceColumns(doc: Document): number {
  let removed = 0
  for (const table of Array.from(doc.querySelectorAll('table'))) {
    if (!/LESSON IMPLEMENTATION FRAMEWORK/i.test(table.textContent ?? '')) continue
    const rows = Array.from(table.querySelectorAll('tr'))
    let resIdx = -1
    let headerLen = -1
    for (const tr of rows) {
      const cells = Array.from(tr.children)
      const idx = cells.findIndex((c) => norm(c.textContent ?? '') === 'Resource')
      if (idx !== -1) {
        resIdx = idx
        headerLen = cells.length
        break
      }
    }
    if (resIdx === -1) continue
    for (const tr of rows) {
      const cells = Array.from(tr.children)
      if (cells.length === headerLen) {
        cells[resIdx].remove()
        removed++
      }
    }
  }
  return removed
}

/** Ordered list of block texts: top-level paragraphs and table cells, in document order. */
export function blocks(doc: Document): string[] {
  const out: string[] = []
  for (const node of Array.from(doc.body.children)) {
    if (node.tagName === 'TABLE') {
      for (const td of Array.from(node.querySelectorAll('td'))) {
        const t = norm(td.textContent ?? '')
        if (t) out.push(t)
      }
    } else {
      const t = norm(node.textContent ?? '')
      if (t) out.push(t)
    }
  }
  return out
}

export async function toBlocks(buf: Buffer, stripResources: boolean): Promise<string[]> {
  const { value: html } = await mammoth.convertToHtml({ buffer: buf })
  const doc = new JSDOM(`<!doctype html><html><body>${html}</body></html>`).window.document
  if (stripResources) stripResourceColumns(doc)
  return blocks(doc)
}

export interface DiffResult {
  match: boolean
  genLen: number
  approvedLen: number
  firstDiff?: { index: number; generated?: string; approved?: string }
}

export function diffBlocks(gen: string[], approved: string[]): DiffResult {
  const n = Math.max(gen.length, approved.length)
  for (let i = 0; i < n; i++) {
    if (gen[i] !== approved[i]) {
      return {
        match: false,
        genLen: gen.length,
        approvedLen: approved.length,
        firstDiff: { index: i, generated: gen[i], approved: approved[i] },
      }
    }
  }
  return { match: true, genLen: gen.length, approvedLen: approved.length }
}

/** Compare a generated DOCX against an approved one, logging the verdict. Returns pass/fail. */
export async function compareDoc(
  label: string,
  generated: Buffer | null,
  approvedBuf: Buffer,
  stripResources: boolean,
): Promise<boolean> {
  console.log(`\n── ${label} ${'─'.repeat(Math.max(0, 40 - label.length))}`)
  if (!generated) {
    console.log('  ✗ generator produced no buffer (data section missing?)')
    return false
  }
  const [gen, approved] = await Promise.all([
    toBlocks(generated, stripResources),
    toBlocks(approvedBuf, stripResources),
  ])
  const r = diffBlocks(gen, approved)
  console.log(
    `  generated bytes: ${generated.length}  | blocks gen=${r.genLen} approved=${r.approvedLen}`,
  )
  if (r.match) {
    console.log(
      `  ✓ CONTENT IDENTICAL${stripResources ? ' (Resource column excluded)' : ''} — ${r.genLen} blocks`,
    )
    return true
  }
  const d = r.firstDiff!
  console.log(`  ✗ MISMATCH at block #${d.index}:`)
  console.log(`      generated: ${JSON.stringify(d.generated)?.slice(0, 300)}`)
  console.log(`      approved : ${JSON.stringify(d.approved)?.slice(0, 300)}`)
  return false
}
