/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    subjects: Subject;
    'subject-grades': SubjectGrade;
    'lesson-bundles': LessonBundle;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    subjects: SubjectsSelect<false> | SubjectsSelect<true>;
    'subject-grades': SubjectGradesSelect<false> | SubjectGradesSelect<true>;
    'lesson-bundles': LessonBundlesSelect<false> | LessonBundlesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Shown for attribution. Non-site-admins never see other emails.
   */
  name: string;
  /**
   * Global Site Administrator grant. Leave empty for non-admins.
   */
  roles?: 'siteAdmin'[] | null;
  /**
   * Per subject-grade grants. Subject Admins may manage only their own subject-grades.
   */
  assignments?:
    | {
        subjectGrade: number | SubjectGrade;
        role: 'subjectAdmin' | 'editor';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subject-grades".
 */
export interface SubjectGrade {
  id: number;
  subject: number | Subject;
  /**
   * Whole number; displayed as "Grade N".
   */
  grade: number;
  /**
   * Auto-generated from subject + grade.
   */
  displayName?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subjects".
 */
export interface Subject {
  id: number;
  /**
   * Academic discipline only, e.g. "Biology". No grade here.
   */
  name: string;
  /**
   * URL-safe identifier, e.g. "biology".
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lesson-bundles".
 */
export interface LessonBundle {
  id: number;
  /**
   * Set automatically on each save.
   */
  semver?: string | null;
  /**
   * Version increment for the next save.
   */
  bumpType?: ('patch' | 'minor' | 'major') | null;
  /**
   * Generation counter — increments on every save.
   */
  lockVersion?: number | null;
  /**
   * Bundle label for lists, e.g. the document title.
   */
  title: string;
  subjectGrade: number | SubjectGrade;
  meta?: {
    subject?: string | null;
    grade?: number | null;
    substrand_id?: string | null;
    substrand_name?: string | null;
    outputDir?: string | null;
    filePrefix?: string | null;
    titleDoc?: string | null;
    subtitleDoc?: string | null;
    col3Label?: string | null;
    col5Label?: string | null;
  };
  /**
   * Sub-strand overview. May be empty.
   */
  unit?: {
    /**
     * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
     */
    overview?: string | null;
  };
  lessons?:
    | {
        /**
         * Set automatically from lesson order.
         */
        number?: number | null;
        /**
         * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
         */
        title?: string | null;
        duration?: string | null;
        substrand?: string | null;
        aresKeywords?: string | null;
        slo?: {
          /**
           * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
           */
          purpose?: string | null;
          /**
           * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
           */
          knowledge?: string | null;
          /**
           * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
           */
          skills?: string | null;
          /**
           * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
           */
          attitudes?: string | null;
          /**
           * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
           */
          keyInquiry?: string | null;
          /**
           * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
           */
          purposeInStoryline?: string | null;
          /**
           * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
           */
          safetyNotes?: string | null;
        };
        /**
         * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
         */
        overview?: string | null;
        framework?:
          | {
              /**
               * Controlled vocabulary — drives colour-coding and resource lookup; an unknown phase silently degrades the document.
               */
              phase:
                | 'Predict Phase'
                | 'Observe Phase'
                | 'Explain Phase'
                | 'Driving Question Board (DQB) Creation'
                | 'Model Building Phase';
              /**
               * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
               */
              learnerExperience?: string | null;
              /**
               * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
               */
              teacherMoves?: string | null;
              /**
               * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
               */
              sensemakingStrategy?: string | null;
              /**
               * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
               */
              formativeAssessment?: string | null;
              /**
               * Auto-resolved at ingest; never user-editable. May be empty.
               */
              resources?: {
                video?: {
                  title?: string | null;
                  direct_url?: string | null;
                  search_url?: string | null;
                };
                reading?: {
                  title?: string | null;
                  direct_url?: string | null;
                  search_url?: string | null;
                };
              };
              id?: string | null;
            }[]
          | null;
        /**
         * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
         */
        teacherReflection?: string | null;
        summaryTablePrompt?: {
          /**
           * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
           */
          observed?: string | null;
          /**
           * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
           */
          learned?: string | null;
          /**
           * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
           */
          explained?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  finalExplanation?: {
    subjectLabel?: string | null;
    /**
     * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
     */
    instructions?: string | null;
    sections?:
      | {
          title?: string | null;
          /**
           * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
           */
          prompt?: string | null;
          /**
           * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
           */
          exemplar?: string | null;
          id?: string | null;
        }[]
      | null;
    rubric?:
      | {
          criterion?: string | null;
          excellent?: string | null;
          proficient?: string | null;
          developing?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  summaryTable?: {
    subStrand?: string | null;
    drivingQuestion?: string | null;
    lessons?:
      | {
          /**
           * Set automatically from row order.
           */
          number?: number | null;
          /**
           * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
           */
          title?: string | null;
          /**
           * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
           */
          observed?: string | null;
          /**
           * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
           */
          learned?: string | null;
          /**
           * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
           */
          explained?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'subjects';
        value: number | Subject;
      } | null)
    | ({
        relationTo: 'subject-grades';
        value: number | SubjectGrade;
      } | null)
    | ({
        relationTo: 'lesson-bundles';
        value: number | LessonBundle;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  assignments?:
    | T
    | {
        subjectGrade?: T;
        role?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subjects_select".
 */
export interface SubjectsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subject-grades_select".
 */
export interface SubjectGradesSelect<T extends boolean = true> {
  subject?: T;
  grade?: T;
  displayName?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lesson-bundles_select".
 */
export interface LessonBundlesSelect<T extends boolean = true> {
  semver?: T;
  bumpType?: T;
  lockVersion?: T;
  title?: T;
  subjectGrade?: T;
  meta?:
    | T
    | {
        subject?: T;
        grade?: T;
        substrand_id?: T;
        substrand_name?: T;
        outputDir?: T;
        filePrefix?: T;
        titleDoc?: T;
        subtitleDoc?: T;
        col3Label?: T;
        col5Label?: T;
      };
  unit?:
    | T
    | {
        overview?: T;
      };
  lessons?:
    | T
    | {
        number?: T;
        title?: T;
        duration?: T;
        substrand?: T;
        aresKeywords?: T;
        slo?:
          | T
          | {
              purpose?: T;
              knowledge?: T;
              skills?: T;
              attitudes?: T;
              keyInquiry?: T;
              purposeInStoryline?: T;
              safetyNotes?: T;
            };
        overview?: T;
        framework?:
          | T
          | {
              phase?: T;
              learnerExperience?: T;
              teacherMoves?: T;
              sensemakingStrategy?: T;
              formativeAssessment?: T;
              resources?:
                | T
                | {
                    video?:
                      | T
                      | {
                          title?: T;
                          direct_url?: T;
                          search_url?: T;
                        };
                    reading?:
                      | T
                      | {
                          title?: T;
                          direct_url?: T;
                          search_url?: T;
                        };
                  };
              id?: T;
            };
        teacherReflection?: T;
        summaryTablePrompt?:
          | T
          | {
              observed?: T;
              learned?: T;
              explained?: T;
            };
        id?: T;
      };
  finalExplanation?:
    | T
    | {
        subjectLabel?: T;
        instructions?: T;
        sections?:
          | T
          | {
              title?: T;
              prompt?: T;
              exemplar?: T;
              id?: T;
            };
        rubric?:
          | T
          | {
              criterion?: T;
              excellent?: T;
              proficient?: T;
              developing?: T;
              id?: T;
            };
      };
  summaryTable?:
    | T
    | {
        subStrand?: T;
        drivingQuestion?: T;
        lessons?:
          | T
          | {
              number?: T;
              title?: T;
              observed?: T;
              learned?: T;
              explained?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}