/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'lesson-plans': LessonPlan;
    'lesson-bundle-versions': LessonBundleVersion;
    subjects: Subject;
    'subject-grades': SubjectGrade;
    users: User;
    favorites: Favorite;
    messages: Message;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'lesson-plans': LessonPlansSelect<false> | LessonPlansSelect<true>;
    'lesson-bundle-versions': LessonBundleVersionsSelect<false> | LessonBundleVersionsSelect<true>;
    subjects: SubjectsSelect<false> | SubjectsSelect<true>;
    'subject-grades': SubjectGradesSelect<false> | SubjectGradesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    favorites: FavoritesSelect<false> | FavoritesSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      generateVersionArtifact: TaskGenerateVersionArtifact;
      emailVersionArtifact: TaskEmailVersionArtifact;
      messagePing: TaskMessagePing;
      passwordResetEmail: TaskPasswordResetEmail;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lesson-plans".
 */
export interface LessonPlan {
  id: number;
  title: string;
  subjectGrade: number | SubjectGrade;
  /**
   * The single global Official version for this lesson plan.
   */
  officialVersion?: (number | null) | LessonBundleVersion;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subject-grades".
 */
export interface SubjectGrade {
  id: number;
  subject: number | Subject;
  /**
   * Whole number; displayed as "Grade N".
   */
  grade: number;
  /**
   * Auto-generated from subject + grade.
   */
  displayName?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subjects".
 */
export interface Subject {
  id: number;
  /**
   * Academic discipline only, e.g. "Biology". No grade here.
   */
  name: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Save writes your edits as a new version — existing versions are never changed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lesson-bundle-versions".
 */
export interface LessonBundleVersion {
  id: number;
  lessonPlan: number | LessonPlan;
  /**
   * Version this snapshot was edited from. Empty for uploaded 1.0.0.
   */
  sourceVersion?: (number | null) | LessonBundleVersion;
  /**
   * Who saved this version. Empty for uploaded or system-created versions.
   */
  author?: (number | null) | User;
  semver: string;
  /**
   * Version label for lists, e.g. the document title.
   */
  title: string;
  subjectGrade: number | SubjectGrade;
  meta?: {
    /**
     * Site Admin only — repair field.
     */
    subject?: string | null;
    /**
     * Site Admin only — repair field.
     */
    grade?: number | null;
    /**
     * Site Admin only — re-uploads of this sub-strand match on it.
     */
    substrand_id?: string | null;
    substrand_name?: string | null;
    outputDir?: string | null;
    filePrefix?: string | null;
    titleDoc?: string | null;
    subtitleDoc?: string | null;
    col3Label?: string | null;
    col5Label?: string | null;
  };
  /**
   * Sub-strand overview. May be empty for some sub-strands.
   */
  unit?: {
    gradeLevel?: string | null;
    subject?: string | null;
    strand?: string | null;
    substrand?: string | null;
    totalDuration?: string | null;
    /**
     * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
     */
    content?: string | null;
    /**
     * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
     */
    learningOutcomes?: string | null;
    /**
     * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
     */
    coreCompetencies?: string | null;
    /**
     * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
     */
    values?: string | null;
    /**
     * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
     */
    sep?: string | null;
    /**
     * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
     */
    pcis?: string | null;
    /**
     * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
     */
    careers?: string | null;
    /**
     * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
     */
    focus?: string | null;
    /**
     * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
     */
    drivingQuestion?: string | null;
    /**
     * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
     */
    phenomenon?: string | null;
    /**
     * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
     */
    supportingPhenomena?: string | null;
    /**
     * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
     */
    storylineThread?: string | null;
  };
  /**
   * Subject Admins may duplicate an existing lesson to add a row. Its system-managed ARES resource links are copied from the source lesson and cannot be edited.
   */
  lessons?:
    | {
        /**
         * Set automatically from lesson order.
         */
        number?: number | null;
        /**
         * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
         */
        title?: string | null;
        duration?: string | null;
        substrand?: string | null;
        aresKeywords?: string | null;
        slo?: {
          /**
           * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
           */
          purpose?: string | null;
          /**
           * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
           */
          knowledge?: string | null;
          /**
           * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
           */
          skills?: string | null;
          /**
           * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
           */
          attitudes?: string | null;
          /**
           * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
           */
          keyInquiry?: string | null;
          /**
           * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
           */
          purposeInStoryline?: string | null;
          /**
           * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
           */
          safetyNotes?: string | null;
        };
        /**
         * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
         */
        overview?: string | null;
        /**
         * Resolved upstream and versioned exactly; never user-editable.
         */
        resourceLinks: {
          phase: 'predict' | 'observe' | 'explain' | 'dqb' | 'model';
          video?: {
            title?: string | null;
            source?: string | null;
            content_type?: string | null;
            direct_url?: string | null;
            search_url?: string | null;
            search_terms?: string | null;
            exact_search_url?: string | null;
            has_transcript?: boolean | null;
            tier?: number | null;
          };
          reading?: {
            title?: string | null;
            source?: string | null;
            content_type?: string | null;
            direct_url?: string | null;
            search_url?: string | null;
            search_terms?: string | null;
            exact_search_url?: string | null;
            has_transcript?: boolean | null;
            tier?: number | null;
          };
          fallback_search_url: string;
          id?: string | null;
        }[];
        framework?:
          | {
              /**
               * Controlled vocabulary — drives colour-coding and resource lookup; an unknown phase silently degrades the document.
               */
              phase?:
                | (
                    | 'Predict Phase'
                    | 'Observe Phase'
                    | 'Explain Phase'
                    | 'Driving Question Board (DQB) Creation'
                    | 'Model Building Phase'
                  )
                | null;
              /**
               * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
               */
              learnerExperience?: string | null;
              /**
               * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
               */
              teacherMoves?: string | null;
              /**
               * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
               */
              sensemakingStrategy?: string | null;
              /**
               * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
               */
              formativeAssessment?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
         */
        teacherReflection?: string | null;
        summaryTablePrompt?: {
          /**
           * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
           */
          observed?: string | null;
          /**
           * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
           */
          learned?: string | null;
          /**
           * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
           */
          explained?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  finalExplanation?: {
    subjectLabel?: string | null;
    /**
     * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
     */
    instructions?: string | null;
    sections?:
      | {
          title?: string | null;
          /**
           * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
           */
          prompt?: string | null;
          /**
           * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
           */
          exemplar?: string | null;
          id?: string | null;
        }[]
      | null;
    rubric?:
      | {
          criterion?: string | null;
          excellent?: string | null;
          proficient?: string | null;
          developing?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  summaryTable?: {
    subStrand?: string | null;
    drivingQuestion?: string | null;
    lessons?:
      | {
          /**
           * Set automatically from row order.
           */
          number?: number | null;
          /**
           * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
           */
          title?: string | null;
          /**
           * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
           */
          observed?: string | null;
          /**
           * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
           */
          learned?: string | null;
          /**
           * Plain text only. A new line starts a new paragraph; a line beginning with "- " becomes a bullet. Markdown/bold/italic are NOT rendered.
           */
          explained?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Shown for attribution. Non-site-admins never see other emails.
   */
  name: string;
  /**
   * Global Site Administrator grant. Leave empty for non-admins.
   */
  roles?: 'siteAdmin'[] | null;
  /**
   * Per subject-grade grants. Subject Admins may manage only their own subject-grades.
   */
  assignments?:
    | {
        subjectGrade: number | SubjectGrade;
        role: 'subjectAdmin' | 'editor';
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites".
 */
export interface Favorite {
  id: number;
  user: number | User;
  version: number | LessonBundleVersion;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  sender: number | User;
  recipient: number | User;
  body: string;
  lessonPlan?: (number | null) | LessonPlan;
  version?: (number | null) | LessonBundleVersion;
  readAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'generateVersionArtifact' | 'emailVersionArtifact' | 'messagePing' | 'passwordResetEmail';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?:
    | ('inline' | 'generateVersionArtifact' | 'emailVersionArtifact' | 'messagePing' | 'passwordResetEmail')
    | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'lesson-plans';
        value: number | LessonPlan;
      } | null)
    | ({
        relationTo: 'lesson-bundle-versions';
        value: number | LessonBundleVersion;
      } | null)
    | ({
        relationTo: 'subjects';
        value: number | Subject;
      } | null)
    | ({
        relationTo: 'subject-grades';
        value: number | SubjectGrade;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'favorites';
        value: number | Favorite;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lesson-plans_select".
 */
export interface LessonPlansSelect<T extends boolean = true> {
  title?: T;
  subjectGrade?: T;
  officialVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lesson-bundle-versions_select".
 */
export interface LessonBundleVersionsSelect<T extends boolean = true> {
  lessonPlan?: T;
  sourceVersion?: T;
  author?: T;
  semver?: T;
  title?: T;
  subjectGrade?: T;
  meta?:
    | T
    | {
        subject?: T;
        grade?: T;
        substrand_id?: T;
        substrand_name?: T;
        outputDir?: T;
        filePrefix?: T;
        titleDoc?: T;
        subtitleDoc?: T;
        col3Label?: T;
        col5Label?: T;
      };
  unit?:
    | T
    | {
        gradeLevel?: T;
        subject?: T;
        strand?: T;
        substrand?: T;
        totalDuration?: T;
        content?: T;
        learningOutcomes?: T;
        coreCompetencies?: T;
        values?: T;
        sep?: T;
        pcis?: T;
        careers?: T;
        focus?: T;
        drivingQuestion?: T;
        phenomenon?: T;
        supportingPhenomena?: T;
        storylineThread?: T;
      };
  lessons?:
    | T
    | {
        number?: T;
        title?: T;
        duration?: T;
        substrand?: T;
        aresKeywords?: T;
        slo?:
          | T
          | {
              purpose?: T;
              knowledge?: T;
              skills?: T;
              attitudes?: T;
              keyInquiry?: T;
              purposeInStoryline?: T;
              safetyNotes?: T;
            };
        overview?: T;
        resourceLinks?:
          | T
          | {
              phase?: T;
              video?:
                | T
                | {
                    title?: T;
                    source?: T;
                    content_type?: T;
                    direct_url?: T;
                    search_url?: T;
                    search_terms?: T;
                    exact_search_url?: T;
                    has_transcript?: T;
                    tier?: T;
                  };
              reading?:
                | T
                | {
                    title?: T;
                    source?: T;
                    content_type?: T;
                    direct_url?: T;
                    search_url?: T;
                    search_terms?: T;
                    exact_search_url?: T;
                    has_transcript?: T;
                    tier?: T;
                  };
              fallback_search_url?: T;
              id?: T;
            };
        framework?:
          | T
          | {
              phase?: T;
              learnerExperience?: T;
              teacherMoves?: T;
              sensemakingStrategy?: T;
              formativeAssessment?: T;
              id?: T;
            };
        teacherReflection?: T;
        summaryTablePrompt?:
          | T
          | {
              observed?: T;
              learned?: T;
              explained?: T;
            };
        id?: T;
      };
  finalExplanation?:
    | T
    | {
        subjectLabel?: T;
        instructions?: T;
        sections?:
          | T
          | {
              title?: T;
              prompt?: T;
              exemplar?: T;
              id?: T;
            };
        rubric?:
          | T
          | {
              criterion?: T;
              excellent?: T;
              proficient?: T;
              developing?: T;
              id?: T;
            };
      };
  summaryTable?:
    | T
    | {
        subStrand?: T;
        drivingQuestion?: T;
        lessons?:
          | T
          | {
              number?: T;
              title?: T;
              observed?: T;
              learned?: T;
              explained?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subjects_select".
 */
export interface SubjectsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subject-grades_select".
 */
export interface SubjectGradesSelect<T extends boolean = true> {
  subject?: T;
  grade?: T;
  displayName?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  assignments?:
    | T
    | {
        subjectGrade?: T;
        role?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "favorites_select".
 */
export interface FavoritesSelect<T extends boolean = true> {
  user?: T;
  version?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  sender?: T;
  recipient?: T;
  body?: T;
  lessonPlan?: T;
  version?: T;
  readAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskGenerateVersionArtifact".
 */
export interface TaskGenerateVersionArtifact {
  input: {
    versionId: number;
    kind: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskEmailVersionArtifact".
 */
export interface TaskEmailVersionArtifact {
  input: {
    versionId: number;
    kind: string;
    to: string;
    requestedByUserId: number;
    requestedByName: string;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskMessagePing".
 */
export interface TaskMessagePing {
  input: {
    messageId: number;
    recipientUserId: number;
    senderUserId: number;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskPasswordResetEmail".
 */
export interface TaskPasswordResetEmail {
  input: {
    userId: number;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}