/**
 * Phase 1 fidelity spike (GATE) — standalone, no Lesson3 DB.
 *
 * Proves the pinned vendored generator regenerates the three approved bio_1_4 DOCX
 * with CONTENT identical to the originals, EXCEPT the Section-C Resource column
 * (which Lesson3 leaves empty — single-runtime, no Python recommender).
 *
 * Run:  cd app && npx tsx scripts/fidelity-spike.ts
 *
 * Diff method: DOCX → HTML via mammoth (the sanctioned DOCX→text tool) → DOM via jsdom →
 * ordered list of block texts (paragraphs + table cells). For the LessonSequence we drop
 * the Resource column from both sides before comparing. We aim for content-identity, not
 * byte/zip-identity (styling/metadata legitimately differ).
 */
import { createRequire } from 'node:module'
import { readFileSync } from 'node:fs'
import path from 'node:path'
import os from 'node:os'
import mammoth from 'mammoth'
import { JSDOM } from 'jsdom'
import { generateBundleDocx } from '../src/generator/index'

const require = createRequire(import.meta.url)

const DEMO = path.join(os.homedir(), 'Desktop', 'ares-docx-fidelity-demo')
// Trusted demo asset (NOT untrusted ingest — the never-execute rule is Phase 3).
const data = require(path.join(DEMO, 'bio_1_4_data.js'))

const APPROVED = {
  lessonSequence: 'Biology_Chemicals_of_Life_CBE_LessonSequence.docx',
  finalExplanation: 'Biology_Chemicals_of_Life_FinalExplanation.docx',
  summaryTable: 'Biology_Chemicals_of_Life_SummaryTable.docx',
} as const

const norm = (s: string) => s.replace(/\s+/g, ' ').trim()

/** Remove the Resource column from every Section-C table (matched by its 'Resource' header). */
function stripResourceColumns(doc: Document): number {
  let removed = 0
  for (const table of Array.from(doc.querySelectorAll('table'))) {
    if (!/LESSON IMPLEMENTATION FRAMEWORK/i.test(table.textContent ?? '')) continue
    const rows = Array.from(table.querySelectorAll('tr'))
    let resIdx = -1
    let headerLen = -1
    for (const tr of rows) {
      const cells = Array.from(tr.children)
      const idx = cells.findIndex((c) => norm(c.textContent ?? '') === 'Resource')
      if (idx !== -1) {
        resIdx = idx
        headerLen = cells.length
        break
      }
    }
    if (resIdx === -1) continue
    for (const tr of rows) {
      const cells = Array.from(tr.children)
      if (cells.length === headerLen) {
        cells[resIdx].remove()
        removed++
      }
    }
  }
  return removed
}

/** Ordered list of block texts: top-level paragraphs and table cells, in document order. */
function blocks(doc: Document): string[] {
  const out: string[] = []
  for (const node of Array.from(doc.body.children)) {
    if (node.tagName === 'TABLE') {
      for (const td of Array.from(node.querySelectorAll('td'))) {
        const t = norm(td.textContent ?? '')
        if (t) out.push(t)
      }
    } else {
      const t = norm(node.textContent ?? '')
      if (t) out.push(t)
    }
  }
  return out
}

async function toBlocks(buf: Buffer, stripResources: boolean): Promise<string[]> {
  const { value: html } = await mammoth.convertToHtml({ buffer: buf })
  const doc = new JSDOM(`<!doctype html><html><body>${html}</body></html>`).window.document
  if (stripResources) stripResourceColumns(doc)
  return blocks(doc)
}

interface DiffResult {
  match: boolean
  genLen: number
  approvedLen: number
  firstDiff?: { index: number; generated?: string; approved?: string }
}

function diffBlocks(gen: string[], approved: string[]): DiffResult {
  const n = Math.max(gen.length, approved.length)
  for (let i = 0; i < n; i++) {
    if (gen[i] !== approved[i]) {
      return {
        match: false,
        genLen: gen.length,
        approvedLen: approved.length,
        firstDiff: { index: i, generated: gen[i], approved: approved[i] },
      }
    }
  }
  return { match: true, genLen: gen.length, approvedLen: approved.length }
}

async function compareDoc(
  label: string,
  generated: Buffer | null,
  approvedFile: string,
  stripResources: boolean,
): Promise<boolean> {
  console.log(`\n── ${label} ${'─'.repeat(Math.max(0, 40 - label.length))}`)
  if (!generated) {
    console.log('  ✗ generator produced no buffer (data section missing?)')
    return false
  }
  const approvedBuf = readFileSync(path.join(DEMO, approvedFile))
  const [gen, approved] = await Promise.all([
    toBlocks(generated, stripResources),
    toBlocks(approvedBuf, stripResources),
  ])
  const r = diffBlocks(gen, approved)
  console.log(`  generated bytes: ${generated.length}  | blocks gen=${r.genLen} approved=${r.approvedLen}`)
  if (r.match) {
    console.log(`  ✓ CONTENT IDENTICAL${stripResources ? ' (Resource column excluded)' : ''} — ${r.genLen} blocks`)
    return true
  }
  const d = r.firstDiff!
  console.log(`  ✗ MISMATCH at block #${d.index}:`)
  console.log(`      generated: ${JSON.stringify(d.generated)?.slice(0, 300)}`)
  console.log(`      approved : ${JSON.stringify(d.approved)?.slice(0, 300)}`)
  return false
}

async function main() {
  console.log('Phase 1 fidelity spike — bio_1_4 (Chemicals of Life)')
  console.log(`META.filePrefix = ${data.META?.filePrefix} | lessons = ${data.LESSONS?.length}`)

  const out = await generateBundleDocx(data)

  const results = [
    await compareDoc('LessonSequence (SoW)', out.lessonSequence, APPROVED.lessonSequence, true),
    await compareDoc('FinalExplanation', out.finalExplanation, APPROVED.finalExplanation, false),
    await compareDoc('SummaryTable', out.summaryTable, APPROVED.summaryTable, false),
  ]

  const passed = results.filter(Boolean).length
  console.log(`\n${'='.repeat(50)}`)
  console.log(`GATE: ${passed}/${results.length} documents content-identical (except Resource column)`)
  if (passed !== results.length) process.exit(1)
  console.log('✓ Phase 1 GATE PASSED')
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})
